import { NextRequest,NextResponse } from "next/server";

export const revalidate=21600;
function key(value:string){return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9 ]/g,"").replace(/\s+/g," ").trim()}
function rows(text:string){const out:string[][]=[];let row:string[]=[],cell="",q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"')q=!q;else if(c===','&&!q){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.length>1)out.push(row);row=[];cell=""}else cell+=c}return out}
export async function GET(request:NextRequest){
  const query=request.nextUrl.searchParams.get("name")?.trim()||"";if(query.length<3)return NextResponse.json({found:false});
  try{
    const positions=["QB","RB","WR","TE"];
    const [maps,statsText]=await Promise.all([Promise.all(positions.map(pos=>fetch(`https://api.sleeper.app/v1/players/nfl?position=${pos}&active=true`,{next:{revalidate:21600}}).then(r=>r.json()))),fetch("https://github.com/nflverse/nflverse-data/releases/download/stats_player/stats_player_week_2025.csv",{next:{revalidate:86400}}).then(r=>r.text())]);
    const candidates=maps.flatMap(map=>Object.values(map) as any[]).filter(p=>p.team&&p.full_name);const exact=candidates.find(p=>key(p.full_name)===key(query));const player=exact||candidates.filter(p=>key(p.full_name).includes(key(query))).sort((a,b)=>(a.search_rank??999999)-(b.search_rank??999999))[0];if(!player)return NextResponse.json({found:false});
    const data=rows(statsText),header=data.shift()||[],ix=(n:string)=>header.indexOf(n),num=(r:string[],n:string)=>Number(r[ix(n)]||0);let passAtt=0,carries=0,teamTargets=0,posTargets=0,qb="Team starter",qbAtt=0,qbTds=0,ownTargets=0,ownCarries=0,ownPpr=0,ownGames=0;const qbTotals=new Map<string,{attempts:number;tds:number}>();
    for(const r of data){if(r[ix("season_type")]!=="REG"||r[ix("team")]!==player.team)continue;const pos=r[ix("position")],attempts=num(r,"attempts"),target=num(r,"targets");passAtt+=attempts;carries+=num(r,"carries");teamTargets+=target;if(pos===player.position)posTargets+=target;if(pos==="QB"&&attempts){const name=r[ix("player_display_name")],old=qbTotals.get(name)||{attempts:0,tds:0};old.attempts+=attempts;old.tds+=num(r,"passing_tds");qbTotals.set(name,old)}if(key(r[ix("player_display_name")]||"")===key(player.full_name)){ownGames++;ownTargets+=target;ownCarries+=num(r,"carries");ownPpr+=num(r,"fantasy_points_ppr")}}
    for(const [name,total] of qbTotals)if(total.attempts>qbAtt){qb=name;qbAtt=total.attempts;qbTds=total.tds}
    const teamPassRate=passAtt+Math.max(0,carries-passAtt*.04)?passAtt/(passAtt+Math.max(0,carries-passAtt*.04)):0.56,positionTargetShare=teamTargets?posTargets/teamTargets:player.position==="WR"?.58:player.position==="TE"?.2:.22,depth=player.depth_chart_order||5;
    const peers=candidates.filter(p=>p.team===player.team&&p.position===player.position&&p.player_id!==player.player_id).sort((a,b)=>(a.depth_chart_order??99)-(b.depth_chart_order??99)||(a.search_rank??999999)-(b.search_rank??999999)).slice(0,6).map(p=>p.full_name);
    const size=Math.max(0,Number(player.weight||190)-180)/25+Math.max(0,Number(player.height||72)-70)*.35,offense=Math.max(-1,Math.min(2,(teamPassRate-.55)*10+(qbTds-25)/20)),role=Math.max(.12,1/Math.pow(depth,1.18));const posBase:any={QB:15,RB:9,WR:8,TE:7},posCeil:any={QB:13,RB:12,WR:13,TE:11};const sample=ownGames?ownPpr/ownGames:0;
    const floor=Math.max(2.5,posBase[player.position]*role*.72+(sample?sample*.35:0));const ceiling=Math.max(floor+5,floor+posCeil[player.position]*Math.sqrt(role)+size+offense);const confidence=Math.max(48,Math.min(76,58+(ownGames?8:0)-(depth-1)*2));const rz=Math.max(45,Math.min(88,60+size*4+offense*4-(depth-1)*4));
    const rank=Math.max(100,Math.min(240,player.search_rank&&player.search_rank<999999?player.search_rank:180));
    return NextResponse.json({found:true,player:{name:player.full_name,pos:player.position,team:player.team,adp:rank,rank,floor:Number(floor.toFixed(1)),ceiling:Number(ceiling.toFixed(1)),confidence:Math.round(confidence),rz:Math.round(rz),role:`On-demand ${player.position}${depth} projection`,note:`Model-generated from ${player.team}'s ${(teamPassRate*100).toFixed(0)}% pass tendency, ${player.position} share of team targets, ${qb}'s 2025 passing profile, current depth competition and ${player.height||"unknown"}-inch/${player.weight||"unknown"}-lb physical profile.`,playerId:player.player_id,depth,depthLabel:player.depth_chart_position||player.position,injuryStatus:player.injury_status||null,age:player.age||null,live:true,modelContext:{height:player.height?`${Math.floor(Number(player.height)/12)}'${Number(player.height)%12}\"`:"Unknown",weight:player.weight?`${player.weight} lb`:"Unknown",college:player.college||"Unknown",teamPassRate,positionTargetShare,quarterback:qb,qbPassTds:qbTds,depthPeers:peers,sample:ownGames?`${ownGames} games · ${ownTargets} targets · ${ownCarries} carries · ${(ownPpr/ownGames).toFixed(1)} PPR/game`:"No verified 2025 NFL usage sample"}}},{headers:{"Cache-Control":"public, s-maxage=21600, stale-while-revalidate=43200"}})
  }catch{return NextResponse.json({found:false},{status:200})}
}
