import {NextRequest,NextResponse} from "next/server";

export const revalidate=300;
function decode(value:string){return value.replace(/<!\[CDATA\[|\]\]>/g,"").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&apos;|&#39;/g,"'").replace(/&quot;/g,'"').replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/\s+/g," ").trim()}
function tag(xml:string,name:string){return decode(xml.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,"i"))?.[1]||"")}
function key(value:string){return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9 ]/g,"").replace(/\s+/g," ").trim()}
const day=(date:Date)=>date.toISOString().slice(0,10);

export async function GET(request:NextRequest){
  const player=request.nextUrl.searchParams.get("player")?.trim()||"",playerId=request.nextUrl.searchParams.get("id")||"";
  if(!player)return NextResponse.json({connected:false,headlines:[],pastUpdates:[],trend:null},{status:400});
  const opts={next:{revalidate:300},signal:AbortSignal.timeout(6000),headers:{"User-Agent":"Mozilla/5.0 (compatible; FourthDownDraftLab/1.0; +https://chatgpt.site)"}};
  const getText=async(url:string)=>{const r=await fetch(url,opts);if(!r.ok)throw new Error(String(r.status));return r.text()},getJson=async(url:string)=>{const r=await fetch(url,opts);if(!r.ok)throw new Error(String(r.status));return r.json()};
  const now=new Date(),cutoff=new Date(now.getTime()-365*86400000),boundaries=Array.from({length:6},(_,i)=>new Date(cutoff.getTime()+(now.getTime()-cutoff.getTime())*i/5));
  const archiveUrls=boundaries.slice(0,-1).map((start,i)=>`https://news.google.com/rss/search?q=${encodeURIComponent(`"${player}" NFL after:${day(start)} before:${day(boundaries[i+1])}`)}&hl=en-US&gl=US&ceid=US:en`);
  const corePromise=Promise.allSettled([getText("https://www.rotowire.com/rss/news.php?sport=NFL"),getText("https://www.espn.com/espn/rss/nfl/news"),getJson("https://site.api.espn.com/apis/site/v2/sports/football/nfl/news?limit=100"),getText(`https://www.bing.com/news/search?q=${encodeURIComponent(`"${player}" NFL`)}&format=rss`),getJson("https://api.sleeper.app/v1/players/nfl/trending/add?lookback_hours=24&limit=100"),getJson("https://api.sleeper.app/v1/players/nfl/trending/drop?lookback_hours=24&limit=100")]);
  const [core,archive]=await Promise.all([corePromise,Promise.allSettled(archiveUrls.map(getText))]);
  const [rotowire,espnRss,espnJson,bingNews,addsResult,dropsResult]=core,needle=key(player),parseRss=(xml:string,source:string)=>[...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(match=>{const item=match[1];return{title:tag(item,"title"),description:tag(item,"description"),url:tag(item,"link")||tag(item,"guid"),published:tag(item,"pubDate"),source}}).filter(item=>key(`${item.title} ${item.description}`).includes(needle));
  const headlines:any[]=[];
  if(rotowire.status==="fulfilled")headlines.push(...parseRss(rotowire.value,"RotoWire"));if(espnRss.status==="fulfilled")headlines.push(...parseRss(espnRss.value,"ESPN"));if(bingNews.status==="fulfilled")headlines.push(...parseRss(bingNews.value,"Bing News"));for(const result of archive)if(result.status==="fulfilled")headlines.push(...parseRss(result.value,"Google News"));
  if(espnJson.status==="fulfilled"){const payload=espnJson.value as any;for(const article of payload.articles||[]){const item={title:article.headline||"",description:article.description||article.story||"",url:article.links?.web?.href||article.links?.api?.news?.href||"",published:article.published||article.lastModified||"",source:"ESPN"};if(key(`${item.title} ${item.description}`).includes(needle))headlines.push(item)}}
  const clusters=new Map<string,any[]>();for(const item of headlines.filter(x=>x.title&&x.url)){const published=Date.parse(item.published||"");if(Number.isFinite(published)&&(published<cutoff.getTime()||published>now.getTime()+86400000))continue;const k=key(item.title.replace(/ - [^-]+$/,"")).slice(0,100);clusters.set(k,[...(clusters.get(k)||[]),item])}
  const quality:Record<string,number>={ESPN:82,RotoWire:80,"Google News":62,"Bing News":62};const unique=[...clusters.values()].map(group=>{const item=group.sort((a,b)=>(quality[b.source]||50)-(quality[a.source]||50))[0],corroboration=new Set(group.map(x=>x.source)).size,parsed=Date.parse(item.published||""),ageHours=Number.isFinite(parsed)?Math.max(0,(Date.now()-parsed)/3600000):9999,freshness=ageHours<=24?12:ageHours<=72?7:ageHours<=336?3:0,reliability=Math.min(99,(quality[item.source]||50)+(corroboration-1)*9+freshness);return{...item,description:String(item.description||"").slice(0,420),reliability,corroboration,label:reliability>=90?"HIGH CONFIDENCE":reliability>=75?"RELIABLE":"SINGLE-SOURCE"}}).sort((a:any,b:any)=>(Date.parse(b.published)||0)-(Date.parse(a.published)||0)),latest=unique.slice(0,6),pastUpdates=unique.slice(6);
  const adds=addsResult.status==="fulfilled"&&Array.isArray(addsResult.value)?addsResult.value:[],drops=dropsResult.status==="fulfilled"&&Array.isArray(dropsResult.value)?dropsResult.value:[],add=adds.find((x:any)=>String(x.player_id)===playerId),drop=drops.find((x:any)=>String(x.player_id)===playerId),archiveLive=archive.filter(x=>x.status==="fulfilled").length;
  const sources=[{name:"RotoWire",live:rotowire.status==="fulfilled",role:"player news",weight:80},{name:"ESPN",live:espnRss.status==="fulfilled"||espnJson.status==="fulfilled",role:"reported news",weight:82},{name:"Google Archive",live:archiveLive>0,role:`${archiveLive}/5 date windows`,weight:62},{name:"Bing News",live:bingNews.status==="fulfilled",role:"independent fallback",weight:62},{name:"Sleeper",live:addsResult.status==="fulfilled"||dropsResult.status==="fulfilled",role:"roster trend",weight:55}];
  return NextResponse.json({connected:sources.some(x=>x.live),updatedAt:new Date().toISOString(),sources,archiveCoverage:{from:day(cutoff),to:day(now),windowsLive:archiveLive,windowsTotal:5,returned:unique.length,complete:archiveLive===5},coverage:{live:sources.filter(x=>x.live).length,total:sources.length,matched:unique.length,rule:"Exact player-name match; five date-bounded archive searches; duplicates clustered across sources."},headlines:latest,pastUpdates,trend:{adds:add?.count||0,drops:drop?.count||0,net:(add?.count||0)-(drop?.count||0),window:"24 hours"}},{headers:{"Cache-Control":"public, s-maxage=300, stale-while-revalidate=900"}})
}
